[package]
name = "rustedbytes-pi"
version = "0.1.0"
edition = "2024"

[dependencies]
dashu = "0.4"
dashu-float = "0.4"
dashu-ratio = "0.4"
dashu-macros = "0.4"
dashu-int = "0.4.1"
dashu-base = "0.4.1"
